name: build_slides

on:
  push:
  pull_request:

jobs:
  build_slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install package
        run: |
          sudo apt-get -y install chromium-browser

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install npm dependencies
        run: npm install decktape && npm install @shd101wyy/mume

      - name: Compile slides
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "x64"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 export.py

      - name: Upload slides
        uses: actions/upload-artifact@v3
        with:
          name: slides
          path: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/export/
